spring:
  application:
    name: server_registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: false
    register-with-eureka: false

  server:
    eviction-interval-timer-in-ms: 30000
