spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://localhost:3306/boi_transaction
    username: root
    password: Aspire@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  kafka:
    bootstrap-servers: 
#      - b-3.bankingmskcluster.canhri.c4.kafka.eu-north-1.amazonaws.com:9092
#      - b-1.bankingmskcluster.canhri.c4.kafka.eu-north-1.amazonaws.com:9092
#      - b-2.bankingmskcluster.canhri.c4.kafka.eu-north-1.amazonaws.com:9092
       localhost:9092
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest 
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.bankofindia.account_service.model.externaldto.TransactionDto:com.bankofindia.transaction_service.model.dto.TransactionDto"        

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8100
